#!/bin/sh
# github.com/fl0at/dotfiles
# Coreutils' base64 is good, but this allows for `base64 "password"`
set -e

# TODO: use printf instead of echo, to use --? Is it portable?

if [ ! -z "$*" ]; then
	echo '$* = ' "$*"
	echo -n "$*" | /usr/bin/base64
else
	if [ -t 0 ]; then # check if stdin
		echo "usage: $0 [string1, string2, ...], or pipe in a file"
		exit 64
	fi
	/usr/bin/base64 < /dev/stdin
fi

