#!/bin/sh
# github.com/fl0at/dotfiles
# Wrap coreutils' base64 to allow for `base64 "password"` as well as the regular redirection :-)
set -e

if [ ! -z "$*" ]; then
	printf "%s" "$*" | /usr/bin/base64
else
	if [ -t 0 ]; then # check if stdin
		echo "usage: $0 [string1, string2, ...], or pipe in a file"
		exit 64
	fi
	/usr/bin/base64 < /dev/stdin
fi

